# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: predector
channels:
  - predector
  - darcyabjones
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## Custom packages
  - apoplastp=1.0.1
  - deeploc=1.0
  - deepsig=0f1e1d9
  - effectorp1=1.0
  - effectorp2=2.0
  - effectorp3=3.0
  - localizer=1.0.4
  - phobius=1.01
  - predectorutils=0.6.0
  - signalp3=3.0b
  - signalp4=4.1g
  - signalp5=5.0b
  - signalp6=1.0
  - targetp2=2.0
  - tmhmm=2.0c
  - r-deepredeff=0.1.1
  ## Conda-forge packages
  - gawk=5.1
  - wget=1.20
  - parallel
  - r-optparse
  ## Fudge to get keras working with deepsig...
  - h5py=2.10.0  # <3
  - tensorflow=2.4.3
  - keras=2.4.3
  ## Bioconda packages
  - emboss=6.6.0
  - hmmer=3.3
  - pfam_scan=1.6
  - mmseqs2=13.45111
  ## Version pins that aren't necessary but make solving environment faster
  - python=3.7.10
  - r-base=4.1
  - perl=5.26.2
  - theano=1.0.4
  - sqlite=3.36.0
  - zlib=1.2.11
  - xz=5.2.5
  - mkl=2020.2
  - hdf5=1.10.6
