# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: predector
channels:
  - predector
  - darcyabjones
  - conda-forge
  - bioconda
dependencies:
  ## Custom packages
  - predector::apoplastp=1.0.1
  - predector::deeploc=1.0
  - predector::deepsig=0f1e1d9
  - predector::effectorp1=1.0
  - predector::effectorp2=2.0
  - predector::effectorp3=3.0=py_2
  - predector::localizer=1.0.4
  - predector::phobius=1.01
  - predector::predectorutils=0.8.2
  - predector::signalp3=3.0b
  - predector::signalp4=4.1g
  - predector::signalp5=5.0b
  - predector::signalp6=6.0e
  - predector::targetp2=2.0
  - predector::tmhmm=2.0c
  - predector::r-deepredeff=0.1.1
  ## Conda-forge packages
  - conda-forge::gawk
  - conda-forge::gzip
  - conda-forge::wget
  - conda-forge::parallel
  - conda-forge::r-optparse
  ## Fudge to get keras working with deepsig...
  - h5py=2.10.0=nompi_*  # <3
  - tensorflow=2.2.0=mkl_*
  - conda-forge::keras=2.4.3
  ## Fudge to keep deepredeff working. Otherwise get error about converting symbolic tensor
  - conda-forge::numpy=1.19.5
  ## some versions of moose install for different versions of perl than the one you're targeting
  ## make sure you pin the versions and check
  ## moose needed for pfamscan
  - bioconda::perl-moose=2.2011
  - conda-forge::perl=5.26.2
  ## Bioconda packages
  - bioconda::emboss=6.6.0
  - bioconda::hmmer=3.3.2
  - bioconda::pfam_scan=1.6
  - bioconda::mmseqs2=13.45111
  ## Version pins that aren't necessary but make solving environment faster
  - conda-forge::pytorch-cpu=1.9.0
  - conda-forge::python=3.6.13
  - conda-forge::r-base=4.1.1
  - conda-forge::sqlite=3.36.0
  - conda-forge::openjdk=11.0.1 
  - conda-forge::theano=1.0.5
  - conda-forge::xz=5.2.5
  - conda-forge::zlib=1.2.11
  - conda-forge::bzip2=1.0.8
  - pip
  - pip:
    - importlib-resources
