{% set version = "2.0" %}

package:
  name: effectorp2
  version: {{ version }}

source:
  url: https://github.com/darcyabjones/EffectorP-2.0/archive/fdfaa2ec9049eb6825861be994a28758f8a902d5.zip
  sha256: 238fdd6dfdeed3f680a0a3ae41721f449430634f864e1ad8f75877bce64e0103

build:
  number: 1
  skip: True  # [win]

requirements:
  run:
    - python =3
    - openjdk
    - emboss
    - numpy

test:
  commands:
    - 'EffectorP.py -h'
    - 'EffectorP2.py -h'
    - 'EffectorP2.py -i "${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/Scripts/Effector_Testing.fasta"'
about:
  home: http://effectorp.csiro.au/
  license: GPL3
  summary: "Improved prediction of fungal effector proteins from secretomes with EffectorP 2.0"
  doc_url: https://github.com/JanaSperschneider/EffectorP-2.0
  dev_url: https://github.com/JanaSperschneider/EffectorP-2.0
