{% set version = "3.0" %}

package:
  name: effectorp3
  version: {{ version }}

source:
  url: "https://github.com/darcyabjones/EffectorP-3.0/archive/53fc798869fe711b2db84540df567558a08139a3.zip"
  sha256: "66fd2839c61efc240c2fdb9b53acf68c53b59f7912ccc7a63b94a83a79cf5c59"

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --compile"
  noarch: python

requirements:
  run:
    - python >=3.6
    - openjdk
  host:
    - python >=3.6
    - openjdk
    - conda-verify

test:
  commands:
    - 'EffectorP.py -h'
    - 'EffectorP3.py -h'
    - "EffectorP3.py -i \"$(python3 -c 'from EP3 import data; print(data.FASTA_PATH)')\""

about:
  home: http://effectorp.csiro.au/
  license: GPL3
  summary: "Improved prediction of fungal effector proteins from secretomes with EffectorP 3.0"
  doc_url: https://github.com/JanaSperschneider/EffectorP-3.0
  dev_url: https://github.com/JanaSperschneider/EffectorP-3.0
