{% set version = "2.0c" %}

package:
  name: tmhmm
  version: {{ version }}

build:
  number: 1
  skip: True  # [not linux]

requirements:
  run:
    - perl

test:
  commands:
    - 'tmhmm -h || [ $? == 1 ]'
    - 'tmhmm2-register || [ $? == 1 ]'

about:
  home: https://services.healthtech.dtu.dk/service.php?TMHMM-2.0
  summary: "A placeholder library to install TMHMM versions 2."
  license: Proprietary

extra:
  recipe-maintainers:
    - darcyabjones
