{% set version = "2.0c" %}

package:
  name: tmhmm
  version: {{ version }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  run:
    - perl

test:
  commands:
    - 'tmhmm -h || [ $? == 1 ]'
    - 'tmhmm-register || [ $? == 1 ]'

about:
  home: https://services.healthtech.dtu.dk/service.php?TMHMM-2.0
