{% set version = "1.01" %}

package:
  name: phobius
  version: {{ version }}

build:
  number: 4
  skip: True  # [not linux]

requirements:
  run:
    - perl
    - patch
    - gzip

test:
  commands:
    - 'phobius.pl -h || [ $? == 1 ]'
    - 'phobius-register || [ $? == 1 ]'

about:
  home: http://phobius.sbc.su.se/
  license: Proprietary

extra:
  recipe-maintainers:
    - darcyabjones
