{% set version = '1.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-effectr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/effectR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/effectR/effectR_{{ version }}.tar.gz
  sha256: 8bf9798b423a7a50fca152f9eb199630ab04106c4f053f5746707494ba0e99c5

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-ggplot2 >=2.2.1
    - r-reshape2
    - r-rmarkdown
    - r-seqinr >=3.3.6
    - r-shiny
    - r-viridis

  run:
    - r-base
    - r-ggplot2 >=2.2.1
    - r-reshape2
    - r-rmarkdown
    - r-seqinr >=3.3.6
    - r-shiny
    - r-viridis
    - hmmer
    - mafft

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('effectR')"           # [not win]
    - "\"%R%\" -e \"library('effectR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=effectR
  license: GPL-2 | GPL-3
  summary: Predicts cytoplasmic effector proteins using genomic data by searching for motifs
    of interest using regular expression searches and hidden Markov models (HMM) based
    in Haas et al. (2009) <doi:10.1038/nature08358>.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: effectR
# Title: Predicts Oomycete Effectors
# Version: 1.0.2
# Authors@R: c(person("Javier", "Tabima", email = "tabimaj@oregonstate.edu", role = c("aut", "cre")),person(c("Niklaus", "J."), "Grunwald", role = "ths", email = "grunwaln@science.oregonstate.edu"))
# Description: Predicts cytoplasmic effector proteins using genomic data by searching for motifs of interest using regular expression searches and hidden Markov models (HMM) based in Haas et al. (2009) <doi:10.1038/nature08358>.
# Depends: R (>= 3.5.0)
# Imports: seqinr (>= 3.3.6), ggplot2 (>= 2.2.1), shiny, reshape2, utils, rmarkdown, viridis
# License: GPL-2 | GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0
# Suggests: knitr, testthat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-09-30 20:56:05 UTC; tabimaj
# Author: Javier Tabima [aut, cre], Niklaus J. Grunwald [ths]
# Maintainer: Javier Tabima <tabimaj@oregonstate.edu>
# Repository: CRAN
# Date/Publication: 2018-09-30 21:30:03 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
