{% set version = "1.0" %}

package:
  name: effectorp1
  version: {{ version }}

source:
  url: https://github.com/darcyabjones/EffectorP-1.0/archive/3e0107f64a371200a6ede7d659c04f507f35af01.zip
  sha256: 3c83393b83bf58b81e0b4b3b749facd3568b7fa793d4a3830a361d9e29f42579

build:
  number: 1
  skip: True  # [win]

requirements:
  run:
    - python =3
    - openjdk
    - emboss

test:
  commands:
    - 'EffectorP.py -h'
    - 'EffectorP1.py -h'
    - 'EffectorP1.py -i "${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/Scripts/Effector_Testing.fasta"'
about:
  home: http://effectorp.csiro.au/
  license: GPL3
