{% set version = "4.1g" %}

package:
  name: signalp4
  version: {{ version }}

build:
  number: 3
  skip: True  # [not linux]

requirements:
  run:
    - patch
    - perl
    - gzip

test:
  commands:
    - 'signalp -h || [ $? == 1 ]'
    - 'signalp4 -h || [ $? == 1 ]'
    - 'signalp4-register || [ $? == 1 ]'

about:
  home: https://services.healthtech.dtu.dk/services/SignalP-4.1#
  summary: "A placeholder library to install SignalP versions 4."
  license: Proprietary

extra:
  recipe-maintainers:
    - darcyabjones
