{% set version = "3.6.12" %}

package:
  name: weka36
  version: {{ version }}

source:
  fn: weka-3-6-12.zip
  url: https://prdownloads.sourceforge.net/weka/weka-3-6-12.zip
  sha256: 504f8ccc0915cd6664eb6aff74bcf5b3796dbdd55917e0b37c3d976cc38eb069

build:
  number: 0
  noarch: generic

requirements:
  run:
    - openjdk

test:
  commands:
    - '[ ! -z "${WEKA36_3_6_12_DIR}" ]'
    - '[ -f "${WEKA36_3_6_12_DIR}/weka.jar" ]'
    - 'java -cp "${WEKA36_3_6_12_JAR}" weka.classifiers.bayes.NaiveBayes -h'
about:
  home: https://www.cs.waikato.ac.nz/ml/weka/index.html
  license: GPL2