{% set version = "1.0.1" %}

package:
  name: apoplastp
  version: {{ version }}

source:
  url: https://github.com/darcyabjones/ApoplastP/archive/8414c0ea35dbd7390eccb44523bbc259957faea7.zip
  sha256: 1005207c5561fc0b30207ac14ab0bd4ad3309bfa72bdfbec5dc2aed0acd5a60b

build:
  number: 1
  skip: true  # [win]

requirements:
  run:
    - python =3
    - openjdk
    - emboss
    - numpy
    - biopython

test:
  commands:
    - 'ApoplastP.py -h'
    - 'ApoplastP.py -i "${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/Scripts/Testing.fasta"'

about:
  home: http://apoplastp.csiro.au/
  summary: "Prediction of effectors and plant proteins in the plant apoplast using machine learning"
  license: GPL3
  doc_url: https://github.com/JanaSperschneider/ApoplastP
  dev_url: https://github.com/JanaSperschneider/ApoplastP
