{% set version = "1.0" %}

package:
  name: signalp6
  version: {{ version }}

build:
  number: 1
  skip: True  # [win]

requirements:
  run:
    - matplotlib>3.3.2
    - numpy>1.19.2
    - pytorch-cpu>1.7.0
    - tqdm>4.46.1

test:
  commands:
    - 'signalp -h || [ $? == 1 ]'
    - 'signalp6 -h || [ $? == 1 ]'
    - 'signalp6-register || [ $? == 1 ]'

about:
  home: https://services.healthtech.dtu.dk/services/signalp-6.0#
  summary: "a placeholder library to install signalp versions 6."
  license: Proprietary

extra:
  recipe-maintainers:
    - darcyabjones
