{% set version = '0.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-deepredeff
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/deepredeff_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/deepredeff/deepredeff_{{ version }}.tar.gz
  sha256: 33a2937e8ed092c8b8d7a902e4b82ddfae56980076f90d180ea6563e58d5ed08

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, kableExtra, knitr, rmarkdown, stringr, testthat
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - bioconductor-biostrings
    - r-dplyr
    - r-ggplot2
    - r-ggthemes
    - r-keras
    - r-magrittr
    - r-purrr
    - r-reticulate
    - r-rlang
    - r-seqinr
    - r-tensorflow >=2.0

  run:
    - r-base
    - bioconductor-biostrings
    - r-dplyr
    - r-ggplot2
    - r-ggthemes
    - r-keras
    - r-magrittr
    - r-purrr
    - r-reticulate
    - r-rlang
    - r-seqinr
    - r-tensorflow >=2.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('deepredeff')"           # [not win]
    - "\"%R%\" -e \"library('deepredeff')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ruthkr/deepredeff/

  license: MIT
  summary: A tool that contains trained deep learning models for predicting effector proteins.
    'deepredeff' has been trained to identify effector proteins using a set of known
    experimentally validated effectors from either bacteria, fungi, or oomycetes. Documentation
    is available via several vignettes, and the paper by Kristianingsih and MacLean
    (2020) <doi:10.1101/2020.07.08.193250>.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: deepredeff
# Title: Deep Learning Prediction of Effectors
# Version: 0.1.1
# Authors@R: person(given = "Ruth", family = "Kristianingsih", role = c("aut", "cre", "cph"), email = "ruth.kristianingsih30@gmail.com", comment = c(ORCID = "0000-0003-1873-6203"))
# Description: A tool that contains trained deep learning models for predicting effector proteins. 'deepredeff' has been trained to identify effector proteins using a set of known experimentally validated effectors from either bacteria, fungi, or oomycetes. Documentation is available via several vignettes, and the paper by Kristianingsih and MacLean (2020) <doi:10.1101/2020.07.08.193250>.
# License: MIT + file LICENSE
# URL: https://github.com/ruthkr/deepredeff/
# BugReports: https://github.com/ruthkr/deepredeff/issues/
# Depends: R (>= 2.10)
# Imports: Biostrings, dplyr, ggplot2, ggthemes, keras, magrittr, purrr, reticulate, rlang, seqinr, tensorflow
# Suggests: covr, kableExtra, knitr, rmarkdown, stringr, testthat
# VignetteBuilder: knitr
# biocViews:
# Config/reticulate: list( packages = list( list(package = "tensorflow", version = "2.0.0", pip = FALSE) ) )
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-07-16 09:12:16 UTC; kristiar
# Author: Ruth Kristianingsih [aut, cre, cph] (<https://orcid.org/0000-0003-1873-6203>)
# Maintainer: Ruth Kristianingsih <ruth.kristianingsih30@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-07-16 09:30:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
